source 'https://rubygems.org'
gem 'github-pages', '~> 215', group: :jekyll_plugins
gem 'kramdown'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-include-cache'
gem 'webrick', '~> 1.7'
